name: Codemod publish

on:
  workflow_dispatch:
  push:
    paths:
      - "codemods/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check prettier
        uses: creyD/prettier_action@v4.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prettier_options: --check

      - name: Install dependencies
        run: pnpm install
      - name: Run test
        run: pnpm recursive run test
  paths-filter:
    name: Check for .codemodrc.json files changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        name: Filter codemods
        with:
          list-files: shell
          filters: |
            codemods:
              - '**/.codemodrc.json'

  publish:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: always() || needs.paths-filter.outputs.codemods == 'true'
    env:
      CODEMOD_API_KEY: ${{ secrets.CODEMOD_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: export files
        run: |
          echo "Modified files: ${{needs.paths-filter.outputs.codemods_files}}"
          echo "Modified status: ${{needs.paths-filter.outputs.codemods}}"
          echo "CODEMOD_STATUS=${{needs.paths-filter.outputs.codemods}}" >> $GITHUB_ENV
          if [ -n "${{needs.paths-filter.outputs.codemods}}" ]; then
            CODEMOD_FILES=$(echo "${{needs.paths-filter.outputs.codemods_files}}" | tr ' ' '\n' | sed "s/.*/'&'/")
            echo "CODEMOD_FILES<<EOF" >> $GITHUB_ENV
            echo "$CODEMOD_FILES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            CODEMOD_FILES=$(find codemods/ -type d -mindepth 1 -maxdepth 1 | sed "s/.*/'&'/")
            echo "CODEMOD_FILES<<EOF" >> $GITHUB_ENV
            echo "$CODEMOD_FILES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install -g codemod

      - name: Run publish codemod
        run: |
          echo "Modified files: $CODEMOD_FILES"
          ROOT_DIR=$(pwd)
          for FILE in $CODEMOD_FILES; do
            DIR=$(dirname "$FILE")
            echo "Checking codemod: $DIR"
            CLEANED_DIR=$(echo "$DIR" | sed "s/^'//;s/'$//")
            cd "$ROOT_DIR/$CLEANED_DIR"
            pnpm install
            npx codemod publish
          done
